blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import PageCreateView, PageListView, PageDetailView, PageUpdateView, PageDeleteView


app_name = BlogConfig.name

urlpatterns = [
    path('create/', PageCreateView.as_view(), name='create'),
    path('', PageListView.as_view(), name='list'),
    path('view/<int:pk>/', PageDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', PageUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', PageDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

NULLABLE = {'null': True, 'blank': True}


class Page(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    body = models.TextField(verbose_name='содержание')
    preview = models.ImageField(upload_to='blog/', verbose_name='превью', **NULLABLE)
    views_count = models.PositiveIntegerField(default=0, verbose_name='просмотры')
    is_published = models.BooleanField(default=True, verbose_name='опубликован')
    slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    date_of_creation = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')

    def __str__(self) -> str:
        return self.title

    class Meta:
        verbose_name='Страница'
        verbose_name_plural = 'Страницы'

blog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from blog.models import Page
from pytils.translit import slugify


class PageCreateView(CreateView):
    model = Page
    fields = ('title', 'body', 'is_published',)
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_pag = form.save()
            new_pag.slug = slugify(new_pag.title)
            new_pag.save()
        return super().form_valid(form)


class PageUpdateView(UpdateView):
    model = Page
    fields = ('title', 'body', 'is_published',)
    success_url = reverse_lazy('blog:list')

    def form_valid(self, form):
        if form.is_valid():
            new_pag = form.save()
            new_pag.slug = slugify(new_pag.title)
            new_pag.save()
        return super().form_valid(form)
    
    def get_success_url(self) -> str:
        return reverse('blog:view', args=[self.kwargs.get('pk')])
    

class PageListView(ListView):
    model = Page

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)  
        queryset = queryset.filter(is_published=True)
        return queryset


class PageDetailView(DetailView):
    model = Page

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class PageDeleteView(DeleteView):
    model = Page    
    success_url = reverse_lazy('blog:list')

blog/templates/blog/page_confirm_delete.html
{% extends "catalog/base.html" %}

{% block  content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p> Хотите удалить страницу "{{ object.title }}"</p>
                        <button type="submit", class="btn btn-danger">Потвердить</button>
                        <a href="{% url 'blog:list' %}" class="btn btn-warning"> Отмена </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/page_detail.html
{% extends "catalog/base.html" %}

{% block  content%}
<div class="col-12">
    <div class="row">
        
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        Материал "{{ object.title }}" ({{ object.slug }})
                    </h3>
                </div>
                <div class="card-body">
                    <p>
                        {{ object.body }}
                    </p>
                </div>
                <div class="card-footer">
                    Просмотры: {{ object.views_count }}
                </div>
            </div>

        </div>
    </div>    
</div>    
{% endblock  %}

blog/templates/blog/page_form.html
{% extends "catalog/base.html" %}

{% block  content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p}}
                        <button type="submit", class="btn btn-success">
                            {% if  object %}
                                Cохранить
                            {% else %}
                                Cоздать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/page_list.html
{% extends 'catalog/base.html' %}

{% block content %}
  <div class="row">
    <div class="col-12 mb-5">
      <a class="btn btn-outline-primary" href="{% url 'blog:create' %}">Создать запись</a>
    </div>
    {% for object in object_list %}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <div class="card-body">
            <p class="card-text">{{ object|title }}</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="{% url 'blog:view' object.pk %}" class="btn btn-sm btn-outline-secondary">View</a>
                <a href="{% url 'blog:edit' object.pk %}" class="btn btn-sm btn-outline-secondary">Edit</a>
                <a href="{% url 'blog:delete' object.pk %}" class="btn btn-sm btn-outline-danger">Delete</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}