blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import PageCreateView, PageListView, PageDetailView, PageUpdateView, PageDeleteView


app_name = BlogConfig.name

urlpatterns = [
    path('create/', PageCreateView.as_view(), name='create'),
    path('', PageListView.as_view(), name='list'),
    path('view/<int:pk>/', PageDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', PageUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', PageDeleteView.as_view(), name='delete'),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from users.views import (LoginView, LogoutView, RegisterView, 
                         VerificationView, ProfileView, RecoveryUpdateView)


app_name = UsersConfig.name


urlpatterns = [
   path('', LoginView.as_view(), name='login'),
   path('logout/', LogoutView.as_view(), name='logout'),
   path('register/', RegisterView.as_view(), name='register'),
   path('verification/', VerificationView.as_view(), name='verification'),
   path('profile/', ProfileView.as_view(), name='profile'),
   path('recovery/', RecoveryUpdateView.as_view(), name='recovery')

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


NULLABLE = {'null': True, 'blank': True}


class User(AbstractUser):
    
    username = None
    email = models.EmailField(unique=True, verbose_name='Email')
    phone = models.CharField(max_length=35, verbose_name='номер телефона', **NULLABLE)
    country = models.CharField(max_length=150, verbose_name='страна', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/views.py
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import View, CreateView, UpdateView, TemplateView
from users.models import User
from users.fotms import UserForm, ProfileForm
from config.settings import EMAIL_HOST_USER
from django.core.mail import send_mail
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.hashers import make_password


class LoginView(BaseLoginView):
    
    template_name = 'users/login.html'


class LogoutView(View):
    
    def get(self, request):
        logout(request)
        return redirect('catalog:index')


class RegisterView(CreateView):
    
    model = User
    form_class = UserForm
    success_url = reverse_lazy('users:login')
    template_name = 'users/register.html'

    def form_valid(self, form):
        
        response = super().form_valid(form)
        new_user = form.save()
        new_user.is_active = False
        new_user.save()
        
        code = new_user.password
        email =  new_user.email
        current_site = get_current_site(self.request)
        
        send_mail(
            'Верификация',
            f'Перейдите по ссылке для верификации: http://{current_site.domain}/users/verification/?source={code}&email={email}',
            EMAIL_HOST_USER,
            [new_user.email]
        )
        
        return response


class ProfileView(UpdateView):
    model = User
    form_class = ProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class RecoveryUpdateView(TemplateView):
    # form_class = RecoveryForm
    template_name = 'users/recovery.html'
    success_url = reverse_lazy('users:login')
    
    def post(self, request):
        email =request.POST.get('email_recovery', '')
        if email != '':
            try:
                user = User.objects.get(email=email)
                new_password = User.objects.make_random_password()
                hash_new_password = make_password(new_password)
                user.password = hash_new_password
                user.save()
                send_mail(
                    'Смена пароля',
                    f'Ваш новый пароль для авторизации: {new_password}',
                    EMAIL_HOST_USER,
                    [user.email]
                )
            except:
                pass    
        return redirect('users:login')


class VerificationView(View):
    
    def get(self, request):
        
        source = request.GET.get('source', '')
        email = request.GET.get('email', '')
        
        try:
            user = User.objects.get(email=email) 
            if user.password == source:
                user.is_active = True
                user.save()      
        except:      
            pass

        return redirect('users:login')

users/templates/users/login.html
{% extends "catalog/base.html" %}

{% block  content%}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">Вход</div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit", class="btn btn-success">Вход</button>
                        <a class="btn btn-danger" href="{% url 'users:recovery' %}">Востановление</a>
                        <a class="btn btn btn-success" href="{% url 'users:register' %}">Регистрация</a>    
                    </form>
                </div>
                <div class="card-footer">
                    
                </div>
            </div>
        </div>
    </div>
{% endblock  %}

users/templates/users/recovery.html
{% extends "catalog/base.html" %}

{% block  content%}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">Востановление</div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <input name="email_recovery" class="form-control mb-3" type="email" placeholder="Введите Emal для востановления" value="">
                        <button type="submit", class="btn btn-success">Востановить</button>
                    </form>
                </div>
                <div class="card-footer">
                    
                </div>
            </div>
        </div>
    </div>
{% endblock  %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% block content %}
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
      <div class="card">
        <div class="card-header">Регистрация</div>
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-success"> Регистрация </button>
          </form>
        </div>
        <div class="card-footer">
        </div>
      </div>
    </div>
  </div>
{% endblock %}

users/templates/users/user_form.html
{%extends 'catalog/base.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <br></br>
    <h4 class="display-4">Редактировать профиль</h4>
</div>
<div class="row">
    <div class="col-4"></div>
    <div class="col-4">
        <div class="card">
            <div class="card-header">Мой профиль</div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </form>
            </div>
            <div class="card-footer">
            </div>
        </div>
    </div>
</div>
{% endblock %}