blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from blog.views import PageCreateView, PageListView, PageDetailView, PageUpdateView, PageDeleteView


app_name = BlogConfig.name

urlpatterns = [
    path('create/', PageCreateView.as_view(), name='create'),
    path('', PageListView.as_view(), name='list'),
    path('view/<int:pk>/', PageDetailView.as_view(), name='view'),
    path('edit/<int:pk>/', PageUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', PageDeleteView.as_view(), name='delete'),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from catalog.apps import CatalogConfig
from catalog.views import (
    ProductListView, 
    ProductDetailView, 
    ContatactTemplateView, 
    ProductCreateView, 
    ProductUpdateView, 
    VersionListView, 
    VersionCreateView, 
    VersionUpdateView, 
    VersionDetailView,
    VersionDeleteView,
    CategoryListView
)


app_name = CatalogConfig.name


urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('contacts/', ContatactTemplateView.as_view(), name='contacts'),
    path('<int:pk>/product/',cache_page(60)(ProductDetailView.as_view()), name='product'),
    path('create_product/', ProductCreateView.as_view(), name='create_product'),
    path('<int:pk>/edit/', ProductUpdateView.as_view(), name='edit_product'),
    path('versions/', VersionListView.as_view(), name='versions'),
    path('<int:pk>/version/', VersionDetailView.as_view(), name='version'),
    path('create_version/', VersionCreateView.as_view(), name='create_version'),
    path('<int:pk>/edit_version/', VersionUpdateView.as_view(), name='edit_version'),
    path('<int:pk>/delete_version/', VersionDeleteView.as_view(), name='delete_version'),
    path('categories/', CategoryListView.as_view(), name='categories'),
]

config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users.apps import UsersConfig
from users.views import (LoginView, LogoutView, RegisterView, 
                         VerificationView, ProfileView, RecoveryUpdateView)


app_name = UsersConfig.name


urlpatterns = [
   path('', LoginView.as_view(), name='login'),
   path('logout/', LogoutView.as_view(), name='logout'),
   path('register/', RegisterView.as_view(), name='register'),
   path('verification/', VerificationView.as_view(), name='verification'),
   path('profile/', ProfileView.as_view(), name='profile'),
   path('recovery/', RecoveryUpdateView.as_view(), name='recovery')

]

catalog/models.py
from django.conf import settings
from django.db import models
from users.models import User


NULLABLE = {'null': True, 'blank': True}


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание')
    image = models.ImageField(upload_to='products/', verbose_name='изображение', **NULLABLE)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=3, decimal_places=0, verbose_name='цена')
    date_of_creation = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    date_of_last_changing = models.DateTimeField(verbose_name='дата последнего изменения', **NULLABLE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Автор', **NULLABLE)
    is_published = models.BooleanField(default=False, verbose_name='Опубликовано')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = "продукт"
        verbose_name_plural = "продукты"
        ordering = ('name',)

        permissions = [
                ('set_is_published', 'Can publish product'),
                ('set_category', 'Can change category'),
                ('set_description', 'Can change description'),
        ]    


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание')

    def __str__(self) -> str:
        return f'{self.pk} {self.name}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('name', )


class Version(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE, verbose_name='Продукт')
    name = models.CharField(max_length=150, verbose_name='Название версии')
    number = models.FloatField(verbose_name='Номер версии')
    is_active = models.BooleanField(default=False, verbose_name='Активна')

    def __str__(self):
        return f'{self.name} {self.number}'
    
    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'
        ordering = ('is_active', 'name',)
        

catalog/forms.py
from django import forms
from catalog.models import Product, Version


class StyleFormMixin:
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):
    forbidden_words = [
        'казино', 
        'криптовалюта', 
        'крипта', 
        'биржа', 
        'дешево', 
        'бесплатно', 
        'обман', 
        'полиция',
        'радар',
    ]

    def check_attribute(self, attribute):
        contains_forbidden_word = [word for word in self.forbidden_words if word in attribute.lower()] 
        if len(contains_forbidden_word) > 0:
            raise forms.ValidationError(f'В поле ввода запрещены слова: {", ".join(contains_forbidden_word)}')
        return attribute

    def clean_name(self):
        data = self.cleaned_data.get('name')
        return self.check_attribute(attribute=data)
    
    def clean_description(self):
        data = self.cleaned_data.get('description')
        return self.check_attribute(attribute=data)

    class Meta:
        model = Product
        fields = (
            'name',
            'description',
            'image',
            'category',
            'price',
        )


class VersionForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'

catalog/views.py
from typing import Any
from django.urls import reverse_lazy
from django.forms import inlineformset_factory
from catalog.models import Product, Version, Category
from catalog.forms import ProductForm, VersionForm
from django.views.generic import (CreateView, UpdateView, DeleteView, 
                                  ListView, DetailView, TemplateView)
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from catalog.services import get_categories
from django.conf import settings
from django.core.cache import cache


class ProductListView(ListView):
    model = Product


class ProductDetailView(DetailView):
    model = Product


class ContatactTemplateView(TemplateView):
    template_name = 'catalog/contacts.html'


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:index') 

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)    
        else:
            context_data['formset'] = VersionFormset(instance=self.object) 
        return context_data
    
    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        self.object.author = self.request.user
        self.object.save()
        if formset.is_valid():
           formset.instance = self.object
           formset.save() 
        return super().form_valid(form)     


class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:index')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)    
        else:
            context_data['formset'] = VersionFormset(instance=self.object) 
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        
        if formset.is_valid():
           formset.instance = self.object
           formset.save()

        return super().form_valid(form)       

    def test_func(self):
        _user = self.request.user
        _instance = self.get_object()
        
        custom_perms = (
            'catalog.set_is_published',
            'catalog.set_category',
            'catalog.set_description',
        )
    
        if _user == _instance.author:
            return True
        elif _user.groups.filter(name='moderator') and _user.has_perms(custom_perms):
            return True
        return self.handle_no_permission()


class VersionListView(ListView):
    model = Version


class VersionDetailView(DetailView):
    model = Version


class VersionCreateView(CreateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy('catalog:versions')


class VersionUpdateView(UpdateView):
    model = Version
    form_class = VersionForm
    success_url = reverse_lazy('catalog:versions')


class VersionDeleteView(DeleteView):
    model = Version    
    success_url = reverse_lazy('catalog:versions')


class CategoryListView(ListView):
    def get_queryset(self, *args, **kwargs):
        if settings.CACHES_ENABLED:
            key = 'categories_list'    
            queryset = cache.get(key)
            if queryset is None:
                queryset = get_categories()
                cache.set(key, queryset)              
        else:
            queryset = get_categories()

        return queryset

catalog/templates/catalog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }
  
        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
      </style>
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:index' %}">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:versions' %}">Версии продукта</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:categories' %}">Категории</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blog:list' %}">Блог</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
        {% if user.is_authenticated %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:logout' %}">Выход</a> 
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:profile' %}">Профиль</a>     
        {% else %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Вход</a>  
        {% endif %}
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>



<div class="container">

    {% block content %}

    {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'catalog:contacts' %}">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}

{% block content %}
  <div class="row">
    {% for object in object_list %}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <div class="card-body">
            <p class="card-text">{{ object.name|title }} </p>
            <p class="card-text"> <b>Описание: </b> </br> {{ object.description|linebreaks }} </p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
              </div>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                    </form>
                    <input type="submit">
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load castom_filter %}
{% block content %}
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    <div class="col">
      <div class="card shadow-sm">
        <img src="{{ object.image|mymedia }}" alt="" width="100%" />

        <div class="card-body">
          <h3>Наименование: {{ object.name }}</h3>
          <div class="d-flex justify-content-between align-items-center">
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
              <li>
                <b>Описание:</b> <br />
                {{ object.description }}
              </li>

              <li>
                <b>Цена за покупку:</b> <br />
                {{ object.price }}
              </li>

              <li>
                <b>Дата создания:</b> <br />
                {{ object.date_of_creation }}
              </li>

              <li>
                <b>Дата последнего изменения:</b> <br />
                {{ object.last_modified_date }}
              </li>

              <li>
                <b>Автор:</b> <br />
                {{ object.author }}
              </li>

            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}
{% block content %}
  <div class="col-12">
    <form method="post" enctype="multipart/form-data">
      <div class="row">
        <div class="col-12 mb-4">
          <button type="submit" class="btn btn-success" enctype="multipart/form-data">Сохранить</button>
        </div>
      </div>
      <div class="row">
        <div class="col-6">
          <div class="card-header">
            <h4>Продукт</h4>
          </div>
          <div class="card-body">
            {% csrf_token %}
            {{ form.as_p }}
          </div>
          <div class="card-footer"></div>
        </div>
        {% if product.author == user or user.is_superuser is True %}
        <div class="col-6">
          <div class="card-header">
            <h4>Версии продута</h4>
          </div>
          <div class="card-body">
            {{ formset.management_form }}
            {% for form in formset.forms %}
              {{ form.as_p }}
            {% endfor %}
          </div>
          <div class="card-footer"></div>
        </div>
        {% endif %}
      </div>
    </form>
  </div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load castom_filter %}
{% block content %}
  <div class="row mb-4">
    {% if user.is_authenticated %}
      <a href="{% url 'catalog:create_product' %}" class="btn btn-success"> + Создать продукт </a>
      {% endif %}
  </div>
  <div class="row">
    {% for object in object_list %}
      <div class="col-4">
        <div class="card mb-4 box-shadow">
          <div class="card-header">
            <h4 class="my-0 font-weight-normal text-center">{{ object.name }}</h4>
          </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title text-center">$ {{ object.price }}</h1>
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
              <li>
                <b>Описание:</b> <br />
                {{ object.description|truncatechars:100 }}
              </li>
              <li>
                <br />
                <ul>
                   <b>Активные версии: </b> <br />
                   {% for version in object.version_set.all|active_version %}
                      <li> {{version.name}} (V:{{ version.number }})</li>
                   {% endfor %} 
                </ul>
              </li>
              <li>
                <p align="center">
                  <br />
                  <a href="{% url 'catalog:product' object.pk %}"><b>Подробнее </b></a> 
                  {% if user.is_authenticated %}   
                    <a href="{% url 'catalog:edit_product' object.pk %}"><b> | Редактировать</b></a>
                  {% endif %}
                </p>
              </li>
            </ul>
            <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/version_confirm_delete.html
{% extends "catalog/base.html" %}

{% block  content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p> Хотите удалить страницу "{{ object.title }}"</p>
                        <button type="submit", class="btn btn-danger">Потвердить</button>
                        <a href="{% url 'catalog:versions' %}" class="btn btn-warning"> Отмена </a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/version_detail.html
{% extends 'catalog/base.html' %}
{% load castom_filter %}
{% block content %}
  <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
    <div class="col">
      <div class="card shadow-sm">
        <img src="{{ object.image|mymedia }}" alt="" width="100%" />

        <div class="card-body">
          <h3>Наименование: {{ object.name }} (V: {{ object.number }})</h3>
          <div class="d-flex justify-content-between align-items-center">
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
              <li>
                <b>Продукт:</b> <br />
                {{ object.product }}
              </li>
              <li>
                <b>Активная:</b> <br />
                {{ object.is_active }}
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

catalog/templates/catalog/version_form.html
{% extends "catalog/base.html" %}
{% block  content %}
    <div class="row">
        <div class="col-11">
           <div class="card-header">
                <h4> Создать Версию продукта </h4>
           </div>
           <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button 
                        type="submit" 
                        class="btn btn-success" 
                        enctype="multipart/form-data"
                    > Сохранить </button>
                </form>
           </div>
           <div class="card-footer"></div> 
        </div>
    </div>    
{% endblock  %}

catalog/templates/catalog/version_list.html
{% extends 'catalog/base.html' %}

{% block content %}
  <div class="row">
    <div class="col-12 mb-5">
      <a class="btn btn-outline-success" href="{% url 'catalog:create_version' %}"> + Создать</a>
    </div>
    {% for object in object_list %}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <div class="card-body">
            <p class="card-text">{{ object.name|title }} (V: {{ object.number }})</p>
            <p class="card-text"> <b>Продукт: </b> {{ object.product }} </p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <a href="{% url 'catalog:version' object.pk %}" class="btn btn-sm btn-outline-secondary">View</a>
                <a href="{% url 'catalog:edit_version' object.pk %}" class="btn btn-sm btn-outline-secondary">Edit</a>
                <a href="{% url 'catalog:delete_version' object.pk %}" class="btn btn-sm btn-outline-danger">Delete</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}